apiVersion: v1
kind: Service
metadata:
  name: bd-airports-svc
  namespace: go
  labels:
    app: go
    name: bd-airports-svc
spec:
  ports:
    - port: 8080
      name: http
      targetPort: 8080
      protocol: TCP
     - port: 17701
       name: metrics
       protocol: TCP
  selector:
    app: go
  type: LoadBalancer
